version: '3.1'
services:
  web-stock:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/web_stock
      - /web_stock/node_modules
      - /web_stock/.next
    command: npm start -- --port 3000
    restart: always
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    restart: always
    ports:
      - 5436:5432
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "postgres",
          "-d",
          "midshiftDB"
        ]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  pgdata:


